apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: encoded-might-480112-k4
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: delivery-cluster-prod
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
