apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: delivery-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: delivery-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: postgres-password
  - secretKey: rabbitmq-password
    remoteRef:
      key: rabbitmq-password
  - secretKey: rabbitmq-user
    remoteRef:
      key: rabbitmq-user
  - secretKey: mongo-uri
    remoteRef:
      key: mongo-uri
  - secretKey: jwt-secret
    remoteRef:
      key: jwt-secret
