# --- AI SERVICE (PYTHON) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        # Python image at Google Artifact Registry
        image: us-central1-docker.pkg.dev/encoded-might-480112-k4/delivery-repo/ai-service:v1
        resources:
          requests:
            cpu: "100m" # Initially allocate 0.1 CPU core
            memory: "128Mi"
          limits:
            cpu: "500m" # Allow up to 0.5 CPU core
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOST
          value: "delivery-rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service # Java will make requests to this service
spec:
  ports:
  - port: 8000
  selector:
    app: ai-service

---
# --- JAVA BACKEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-engine
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: delivery-engine
  template:
    metadata:
      labels:
        app: delivery-engine
    spec:
      containers:
      - name: delivery-engine
        # Java image at Google Artifact Registry
        image: us-central1-docker.pkg.dev/encoded-might-480112-k4/delivery-repo/java-backend:v1
        resources:
          requests:
            cpu: "250m" # Java starts with 0.25 CPU core
            memory: "768Mi"
          limits:
            cpu: "2000m" # Allow up to 2 CPU core
            memory: "1536Mi" # Allow up to 1.5 GB memory
        ports:
        - containerPort: 8080
        env:
        # 1. Inform Spring Boot that it's behind a proxy and to trust the headers
        - name: SERVER_FORWARD_HEADERS_STRATEGY
          value: "framework"      
        # 2. Accept proxy information from all IP addresses
        - name: SERVER_TOMCAT_REMOTEIP_INTERNAL_PROXIES
          value: ".*"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://delivery-postgres:5432/deliverydb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: delivery-secrets
              key: postgres-password
        - name: SPRING_DATA_REDIS_HOST
          value: "delivery-redis"
        - name: SPRING_RABBITMQ_HOST
          value: "delivery-rabbitmq"
        - name: APP_AI_SERVICE_URL
          value: "http://ai-service:8000" # Call service by name
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-engine-service
spec:
  type: LoadBalancer # Get an IP for external access
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: delivery-engine