apiVersion: v1
kind: Secret
metadata:
  name: delivery-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | quote }}
  rabbitmq-user: {{ .Values.secrets.rabbitmqUser | quote }}
  mongo-uri: {{ .Values.secrets.mongoUri | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}