apiVersion: v1
kind: Service
metadata:
  name: {{ include "delivery-app.fullname" . }}-backend
  labels:
    {{- include "delivery-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: {{ include "delivery-app.fullname" . }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "delivery-app.fullname" . }}-ai
  labels:
    {{- include "delivery-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ai.service.type }}
  ports:
  - port: {{ .Values.ai.service.port }}
    targetPort: {{ .Values.ai.containerPort }}
  selector:
    app: {{ include "delivery-app.fullname" . }}-ai
